# Use postgres/example user/password credentials
version: '3.1'

services:

  pizzalab:
    image: pizza-lab:v2
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: pizzalab-postgres
    restart: always
    ports:
      - "8432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: pizzalab
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d pizzalab -U user" ]
      interval: 30s
      timeout: 30s
      retries: 3

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080
